### PR TITLE
Bump to OpenCart 3.0

### PR DESCRIPTION
**Pull request by vitormattos**
- upgrade OpenCart version to 3.0.1.1
- upgrade all dependencies to newest versions
- add PHPCS
- fix tests to correct work with new OpenCart version
- remove dependencies from beyondit repository in `.travis.yml`
This change require add environments in Travis-CI website to correctly CI work
- PSR-2

### CODE REVIEW

**Comment by vitormattos** [comment]
Look the latest build in my [Travis-CI](https://travis-ci.org/vitormattos/opencart-test-suite/builds/254016491)

**Comment by stefanhuber** [comment]
thx @vitormattos  for your great contribution! i will check that asap, i am currently on holidays...

**Comment by stefanhuber** [comment]
@vitormattos Can you explain me why adding environment variables inside the settings of travis is better then leaving them inside the .travis conig file? I am not sure why one should do that?

**Comment by vitormattos** [comment]
In old version of .travis has the path to your repository, it was not possible test in my travis without change the .travis file for this reason. If the environment with the path is stored outside of versioned files, is possible makes able to test with my own travis account during development.

**Comment by vitormattos** [comment]
Now is necessary create new branch and tag to version 3.0 in dev branch.

**Comment by stefanhuber** [comment]
Ahh, I understand, good point!
Released on packagist: https://packagist.org/packages/beyondit/opencart-test-suite

**Pull request merged**
